spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: ${DB_DEMO_URL}
    password: ${DB_DEMO_PASSWD}
    username: ${DB_DEMO_USER}
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 5
      maximum-pool-size: 50
      idle-timeout: 30000
      pool-name: DatebookHikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1
  jpa:
    show-sql: true
    generate-ddl: true
#    database: mysql

  devtools:
    restart:
      enabled: true
#  mvc:
#    view:
#      prefix: /templates/
#      suffix: .jsp
#    static-path-pattern: /**
#  resources:
#    static-locations: /static/

server:
  port: 9000

soa:
  zookeeper:
    host: 127.0.0.1:2181

