spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: ${DB_DEMO_URL}
    password: ${DB_DEMO_PASSWD}
    username: ${DB_DEMO_USER}
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 5
      maximum-pool-size: 50
      idle-timeout: 30000
      pool-name: DatebookHikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1
  jpa:
    show-sql: true
  devtools:
    restart:
      enabled: true
server:
  port: 9000

