spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: ${DB_MOCK_DB_URL}
    password: ${DB_MOCK_DB_PASSWD}
    username: ${DB_MOCK_DB_USER}
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 5
      maximum-pool-size: 50
      idle-timeout: 30000
      pool-name: DatebookHikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1
  jpa:
    show-sql: true
    generate-ddl: true
    properties:
      hibernate:
        format_sql: true



  #  spring.security.user.name=admin
  #  spring.security.user.password=123

  #    database: mysql

  devtools:
    restart:
      enabled: true
  mvc:
    view:
      prefix: /views/
      suffix: .jsp
    static-path-pattern: /**
  resources:
    static-locations: /static/
  servlet:
    multipart:
      max-file-size: 10MB
  security:
    user:
      name: maple
      password: 123456

server:
  port: 9000
  tomcat:
    remote-ip-header: X-Real-IP
    protocol-header: X-Forwarded-Proto
  use-forward-headers: true

soa:
  zookeeper:
    host: 127.0.0.1:2181

# spring actuator config
management:
  endpoint:
    shutdown:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"

